import Head from "next/head";
import Header from "@/components/header";
import Main from "@/components/main";
import FooterSection from "@/components/footer";
import Layout from "@/components/layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Glacier Windows & Doors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout />
    </>
  );
}
